### ISSUE TITLE
How to load assets folder image in rich TextView

### ISSUE THREAD

**Issue by lovebdsobuj** [hidroh/richtext#1]
How to load `assets` or `res/drawable` folder image in rich TextView?

**Comment by hidroh** [comment]
You can either set the drawable as `drawableTop`, `drawableBottom`, `drawableLeft` or `drawableRight` if that is sufficient. Otherwise you can embed it in `<img>` HTML tag, in which `src` points to a custom URI that you can parse and extract the drawable in your own `ImageGetter` while you parse HTML.
